[2024-03-05T22:11:14.811-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Enviando-relatorio scheduled__2024-03-04T09:00:00+00:00 [queued]>
[2024-03-05T22:11:14.822-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Enviando-relatorio scheduled__2024-03-04T09:00:00+00:00 [queued]>
[2024-03-05T22:11:14.822-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-05T22:11:14.848-0300] {taskinstance.py:2214} INFO - Executing <Task(DatabricksRunNowOperator): Enviando-relatorio> on 2024-03-04 09:00:00+00:00
[2024-03-05T22:11:14.853-0300] {standard_task_runner.py:60} INFO - Started process 62014 to run task
[2024-03-05T22:11:14.858-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Enviando-relatorio', 'scheduled__2024-03-04T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpxj1wn5s7']
[2024-03-05T22:11:14.860-0300] {standard_task_runner.py:88} INFO - Job 7: Subtask Enviando-relatorio
[2024-03-05T22:11:14.969-0300] {task_command.py:423} INFO - Running <TaskInstance: Executando-notebook-etl.Enviando-relatorio scheduled__2024-03-04T09:00:00+00:00 [running]> on host GabGalani.
[2024-03-05T22:11:15.166-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Executando-notebook-etl' AIRFLOW_CTX_TASK_ID='Enviando-relatorio' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-04T09:00:00+00:00'
[2024-03-05T22:11:15.174-0300] {base.py:83} INFO - Using connection ID 'databricks_default' for task execution.
[2024-03-05T22:11:15.200-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:11:15.646-0300] {databricks.py:54} INFO - Run submitted with run_id: 241157687327125
[2024-03-05T22:11:15.647-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:11:15.900-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:11:16.112-0300] {databricks.py:108} INFO - Enviando-relatorio in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2024-03-05T22:11:16.113-0300] {databricks.py:109} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/633014441347933/run/241157687327125
[2024-03-05T22:11:16.113-0300] {databricks.py:110} INFO - Sleeping for 30 seconds.
[2024-03-05T22:11:46.144-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:11:46.421-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:11:46.836-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 831, in execute
    _handle_databricks_operator_execution(self, hook, self.log, context)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 105, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: Enviando-relatorio failed with terminal state: {'life_cycle_state': 'INTERNAL_ERROR', 'result_state': 'FAILED', 'state_message': 'Task 3-automatizando-envio failed with message: Workload failed, see run output for details. This caused all downstream tasks to get skipped.'} and with the error ModuleNotFoundError: No module named 'slack_Sdk'
[2024-03-05T22:11:46.839-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Executando-notebook-etl, task_id=Enviando-relatorio, execution_date=20240304T090000, start_date=20240306T011114, end_date=20240306T011146
[2024-03-05T22:11:46.855-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task Enviando-relatorio (Enviando-relatorio failed with terminal state: {'life_cycle_state': 'INTERNAL_ERROR', 'result_state': 'FAILED', 'state_message': 'Task 3-automatizando-envio failed with message: Workload failed, see run output for details. This caused all downstream tasks to get skipped.'} and with the error ModuleNotFoundError: No module named 'slack_Sdk'; 62014)
[2024-03-05T22:11:46.885-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T22:11:46.895-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T22:26:08.519-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Enviando-relatorio scheduled__2024-03-04T09:00:00+00:00 [queued]>
[2024-03-05T22:26:08.528-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Enviando-relatorio scheduled__2024-03-04T09:00:00+00:00 [queued]>
[2024-03-05T22:26:08.529-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-05T22:26:08.551-0300] {taskinstance.py:2214} INFO - Executing <Task(DatabricksRunNowOperator): Enviando-relatorio> on 2024-03-04 09:00:00+00:00
[2024-03-05T22:26:08.554-0300] {standard_task_runner.py:60} INFO - Started process 67447 to run task
[2024-03-05T22:26:08.557-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Enviando-relatorio', 'scheduled__2024-03-04T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpw43i41pe']
[2024-03-05T22:26:08.559-0300] {standard_task_runner.py:88} INFO - Job 7: Subtask Enviando-relatorio
[2024-03-05T22:26:08.606-0300] {task_command.py:423} INFO - Running <TaskInstance: Executando-notebook-etl.Enviando-relatorio scheduled__2024-03-04T09:00:00+00:00 [running]> on host GabGalani.
[2024-03-05T22:26:08.704-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Executando-notebook-etl' AIRFLOW_CTX_TASK_ID='Enviando-relatorio' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-04T09:00:00+00:00'
[2024-03-05T22:26:08.712-0300] {base.py:83} INFO - Using connection ID 'databricks_default' for task execution.
[2024-03-05T22:26:08.740-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:26:09.180-0300] {databricks.py:54} INFO - Run submitted with run_id: 382280150753867
[2024-03-05T22:26:09.181-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:26:09.497-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:26:09.702-0300] {databricks.py:108} INFO - Enviando-relatorio in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2024-03-05T22:26:09.703-0300] {databricks.py:109} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/633014441347933/run/382280150753867
[2024-03-05T22:26:09.704-0300] {databricks.py:110} INFO - Sleeping for 30 seconds.
[2024-03-05T22:26:39.725-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T22:26:40.012-0300] {databricks.py:65} INFO - Enviando-relatorio completed successfully.
[2024-03-05T22:26:40.013-0300] {databricks.py:66} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/633014441347933/run/382280150753867
[2024-03-05T22:26:40.018-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Executando-notebook-etl, task_id=Enviando-relatorio, execution_date=20240304T090000, start_date=20240306T012608, end_date=20240306T012640
[2024-03-05T22:26:40.038-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-05T22:26:40.050-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
